# Generated by Django 4.1.3 on 2022-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servico",
            name="procolo",
        ),
        migrations.AddField(
            model_name="servico",
            name="protocolo",
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
