# Generated by Django 4.1.3 on 2022-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="ano",
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carro",
            name="placa",
            field=models.CharField(max_length=8),
        ),
    ]
